# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pass_gen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setItalic(True)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QFrame#frame{\n"
"background-color: rgb(85, 85, 127);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton#generate{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.142045 rgba(89, 241, 224, 255), stop:0.511364 rgba(67, 241, 131, 255), stop:0.9375 rgba(255, 238, 0, 255));\n"
"border-radius:15px;\n"
"border: 2px solid rgb(52, 0, 79);\n"
"}\n"
"\n"
"QPushButton#closeApp{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:hover#closeApp{\n"
"border:2px solid rgb(210, 35, 42);\n"
"border-radius:12px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover#generate{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0738636 rgba(255, 238, 0, 255), stop:0.511364 rgba(67, 241, 131, 255), stop:0.846591 rgba(89, 241, 224, 255));\n"
"}\n"
"\n"
"QLineEdit#password_len{\n"
"background-color: transparent;\n"
"border-bottom:2px solid rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus#password_len{\n"
"border:2px solid rgb(85, 0, 127);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QLineEdit#result{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 238, 0, 255), stop:0.539773 rgba(67, 241, 131, 255), stop:0.926136 rgba(39, 255, 194, 255));\n"
"border-radius:10px;\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(15, 15, 370, 370))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.generate = QtWidgets.QPushButton(self.frame)
        self.generate.setGeometry(QtCore.QRect(110, 290, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.generate.setFont(font)
        self.generate.setObjectName("generate")
        self.password_len = QtWidgets.QLineEdit(self.frame)
        self.password_len.setGeometry(QtCore.QRect(154, 249, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.password_len.setFont(font)
        self.password_len.setText("")
        self.password_len.setMaxLength(16)
        self.password_len.setAlignment(QtCore.Qt.AlignCenter)
        self.password_len.setObjectName("password_len")
        self.result = QtWidgets.QLineEdit(self.frame)
        self.result.setGeometry(QtCore.QRect(40, 130, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.result.setFont(font)
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(131, 269, 114, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 180, 231, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.form = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.form.setContentsMargins(0, 0, 0, 0)
        self.form.setObjectName("form")
        self.specSym = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.specSym.setObjectName("specSym")
        self.form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.specSym)
        self.bigSym = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.bigSym.setObjectName("bigSym")
        self.form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bigSym)
        self.smallSym = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.smallSym.setObjectName("smallSym")
        self.form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.smallSym)
        self.numbers = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.numbers.setObjectName("numbers")
        self.form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.numbers)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.closeApp = QtWidgets.QPushButton(self.frame)
        self.closeApp.setGeometry(QtCore.QRect(340, 10, 26, 24))
        self.closeApp.setStyleSheet("")
        self.closeApp.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/i-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeApp.setIcon(icon)
        self.closeApp.setIconSize(QtCore.QSize(33, 35))
        self.closeApp.setObjectName("closeApp")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generate.setText(_translate("MainWindow", "GENERATE"))
        self.result.setText(_translate("MainWindow", "result"))
        self.label.setText(_translate("MainWindow", "Password length"))
        self.specSym.setText(_translate("MainWindow", " спец символы"))
        self.bigSym.setText(_translate("MainWindow", "заглавные буквы"))
        self.smallSym.setText(_translate("MainWindow", "строчные буквы"))
        self.numbers.setText(_translate("MainWindow", "цифры"))
        self.label_2.setText(_translate("MainWindow", "<strong>PASSWORD</strong> GENERATOR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
